[package]
name = "graphics_year2"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
rayon = "1.5.1"
rand = "0.8.5"

[release.profile]
opt-level=3
codegen-unit=1
lto="fat"
